project:
    type: book
    output-dir: docs

book:
    title: Time Series Analysis
    subtitle: Lecture Notes with Examples in R
    author: V. Lyubchich and Y. R. Gel
    # date: today
    date-format: iso
    favicon: tsar_fav.png
    cover-image: tsar_cov.png
    repo-url: https://github.com/vlyubchich/tsar/
    repo-branch: master
    repo-actions: [edit, issue]
  # downloads: [pdf, epub]
  # sharing: [twitter, facebook]
    page-navigation: true
    reader-mode: true
    sidebar:
        search: true
    chapters:
        - index.qmd
        - l01_regression.qmd
        - l02_tsintro.qmd
        - l03_smoothing.qmd
        - l04_arma.qmd
        - l05_arima.qmd
        - l06_garch.qmd
        - l07_trendtest.qmd
        - l08_tsreg1.qmd
        - l09_tsreg2.qmd
        # - l10_causality.qmd
        # - l11_panel.qmd
        - l12_forecast.qmd
        - l13_spectral.qmd
        - software.qmd
        - references.qmd
    appendices:
        - s1_wls.qmd
        - s2_gls.qmd
        - s4_trendsync.qmd
        # - s6_extremes.qmd
        - s7_garma.qmd
        - s_practice.qmd

bibliography:
    - references.bib
    - refpackages.bib
csl: springerbasicVL.csl

appendix-style: default

format:
    html:
        code-fold: true
        code-link: true
        theme: cosmo
        fig-width: 8
        fig-height: 5

engine: knitr
knitr:
    opts_chunk:
        collapse: false
        message: false
        warning: false
        comment: "#>"
        R.options:
            knitr.graphics.auto_pdf: true
execute:
    eval: true
    echo: true
